"""Prometheus metrics for agent observability instrumentation."""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

spans_total = Counter(
    "agent_obs_spans_total",
    "Spans enqueued for export",
    ["agent_id"],
)

dropped_spans_total = Counter(
    "agent_obs_dropped_spans_total",
    "Spans dropped due to full ring buffer",
    ["agent_id"],
)

exporter_errors_total = Counter(
    "agent_obs_exporter_errors_total",
    "Exporter errors by type",
    ["exporter", "status_code"],
)

cost_per_request_usd = Gauge(
    "agent_obs_cost_per_request_usd",
    "Cost of the last completed LLM call in USD",
    ["agent_id", "model"],
)

cost_total_usd = Counter(
    "agent_obs_cost_total_usd",
    "Accumulated total cost of all LLM calls in USD",
    ["agent_id", "model"],
)

guardrail_block_total = Counter(
    "agent_obs_guardrail_block_total",
    "Guardrail blocks raised before a guarded call, by stage",
    ["stage"],
)

guardrail_check_in_enqueue_total = Counter(
    "agent_obs_guardrail_check_in_enqueue_total",
    "Guardrail text checks performed inside _enqueue (last-resort masking barrier)",
)

eval_llm_judge_pending_total = Counter(
    "agent_obs_eval_llm_judge_pending_total",
    "LLM judge evaluation jobs enqueued for async processing",
    ["eval_name"],
)

eval_llm_judge_sampling_skipped_total = Counter(
    "agent_obs_eval_llm_judge_sampling_skipped_total",
    "LLM judge evaluations skipped due to sampling rate",
)

eval_annotation_total = Counter(
    "agent_obs_eval_annotation_total",
    "Late annotation writes to ClickHouse",
    ["status"],
)

eval_annotation_redis_fallback_total = Counter(
    "agent_obs_eval_annotation_redis_fallback_total",
    "Late annotations stored in Redis due to ClickHouse unavailability",
)

eval_jobs_completed_total = Counter(
    "agent_obs_eval_jobs_completed_total",
    "LLM judge jobs completed successfully",
)

eval_jobs_failed_total = Counter(
    "agent_obs_eval_jobs_failed_total",
    "LLM judge jobs that failed",
)

eval_job_latency_seconds = Histogram(
    "agent_obs_eval_job_latency_seconds",
    "LLM judge job processing latency",
    buckets=[1, 2, 5, 10, 15, 30, 60],
)

# --- Cron maintenance jobs (PC21) -------------------------------------------
# These are emitted by the out-of-process cron service (scripts/cron/scheduler.py),
# never by the SDK in-process. `job_name` is a bounded set: cleanup_vault,
# cleanup_audit_events, cleanup_eval_results.

cron_runs_total = Counter(
    "agent_obs_cron_runs_total",
    "Cron maintenance job runs started",
    ["job_name"],
)

cron_errors_total = Counter(
    "agent_obs_cron_errors_total",
    "Cron maintenance job runs that failed",
    ["job_name"],
)

cron_rows_deleted_total = Counter(
    "agent_obs_cron_rows_deleted_total",
    "Rows deleted or archived by a cron maintenance job",
    ["job_name"],
)

cron_duration_seconds = Histogram(
    "agent_obs_cron_duration_seconds",
    "Cron maintenance job wall-clock duration",
    ["job_name"],
    buckets=[0.5, 1, 2.5, 5, 10, 30, 60, 300, 900],
)

cron_last_success_timestamp_seconds = Gauge(
    "agent_obs_cron_last_success_timestamp_seconds",
    "Unix timestamp of the last successful cron maintenance run",
    ["job_name"],
)

# --- PC23 Warm→Cold migration metrics ---
migration_warm_to_cold_files_total = Counter(
    "agent_obs_migration_warm_to_cold_files_total",
    "Parquet files written to cold storage",
    ["job_name"],
)

migration_warm_to_cold_rows_total = Counter(
    "agent_obs_migration_warm_to_cold_rows_total",
    "Trace rows aggregated into cold storage",
    ["job_name"],
)

migration_warm_to_cold_bytes_total = Counter(
    "agent_obs_migration_warm_to_cold_bytes_total",
    "Bytes written to cold storage",
    ["job_name"],
)

migration_warm_to_cold_duration_seconds = Histogram(
    "agent_obs_migration_warm_to_cold_duration_seconds",
    "Cold migration job wall-clock duration",
    ["job_name"],
    buckets=[1, 5, 15, 30, 60, 300, 900, 3600],
)

# --- PC24 Embedding storage metrics ------------------------------------------

embeddings_stored_total = Counter(
    "agent_obs_embeddings_stored_total",
    "Response embeddings successfully written to ClickHouse",
)

embeddings_storage_failed_total = Counter(
    "agent_obs_embeddings_storage_failed_total",
    "Embedding writes to ClickHouse that failed",
)

embeddings_batch_size = Histogram(
    "agent_obs_embeddings_batch_size",
    "Number of embeddings in each ClickHouse batch write",
    buckets=[1, 5, 10, 25, 50, 100, 250, 500],
)

# --- PC25 Drift detection metrics ---

drift_kl_score = Gauge(
    "agent_obs_drift_kl_score",
    "Current KL-divergence score for drift detection",
    ["agent_id"],
)

drift_runs_total = Counter(
    "agent_obs_drift_runs_total",
    "Drift detection runs completed",
    ["agent_id"],
)

drift_alerts_total = Counter(
    "agent_obs_drift_alerts_total",
    "Drift alerts generated by severity",
    ["agent_id", "severity"],
)
